baseurl: "https://wmyang.netlify.app/"
languageCode: en-us
title: "Weimin Yang "
theme: "hugo-ivy"
# googleAnalytics: ""
# disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
# preserveTaxonomyNames: true
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: ↩
rssLimit: 10

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"
  #note: /note/:year/:month/:day/:slug/
  #post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "菜谱"
      url: "/cn/recipe/"
      weight: 5
    - name: "货币即艺术"
      url: "/cn/money/"
      #url: "/cn/kids/"
      weight: 6
    - name: "English"
      url: "/en/"
      weight: 7 
      

params:
  description: "Welcome! Personal website of Weimin Yang"
  footer: "&copy; [Weimin Yang](https://wmyang.netlify.app) {Year} | [Github](https://github.com/weimin3)"
  #footer: "&copy; [Weimin Yang](https://wmyang.netlify.app) {Year} "
  customJS:
    - "comment-utils.js"
    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
    - "external-link.js"
    - "alt-title.js"
    - "header-link.js"
  #githubContentURL: "https://github.com/yihui/yihui.org/edit/master/content/"
  
  
  highlightjsLang: ["latex"]
  #highlightjsTheme: "github"
  highlightjsTheme: "base16/heetch-light"
  highlightjsVersion: "11.7.0"
  
   logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Weimin Yang"
      tag: ""
   

  author:
    en: "Weimin Yang"
    cn: "杨尚豫"
    

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
